version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    networks:
      - flipkart-network

  frontend-angular:
    build: ./frontend-angular
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - flipkart-network

  frontend-react:
    build: ./frontend-react
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - flipkart-network

networks:
  flipkart-network:
    driver: bridge
